### ISSUE TITLE
Unnecessary alignment with danger of memory leak

### ISSUE THREAD

**Issue by mkstoyanov** [dannys4/FFT-Research-F20#3]
https://github.com/dannys4/FFT-Research-F20/blob/a6a45f6c761b5d84122a1cb1261231d6df839328/FFTE/include/complex.hpp#L109

You don't need to use aligned memory here, you can always read/write to unalined memory and I/O doesn't have to be fast. Without alignment, you can also use RAII or stack memory, e.g.,
```
         double tmp[2];
        _mm_storeu_pd(tmp, dt.getVar());
```

**Comment by dannys4** [comment]
This issue is now addressed in commit [018d7a92f3ce84094cf0840a397d6b6a151a8578](https://github.com/dannys4/FFT-Research-F20/commit/018d7a92f3ce84094cf0840a397d6b6a151a8578)
