### ISSUE TITLE
Namespace everything

### ISSUE THREAD

**Issue by mkstoyanov** [dannys4/FFT-Research-F20#5]
https://github.com/dannys4/FFT-Research-F20/blob/a6a45f6c761b5d84122a1cb1261231d6df839328/FFTE/include/algos.hpp#L1

C++ code should sit in an appropriate namespace, e.g.,
```
namepace FFTE{
}
```
But macros and C-style of functions should be namespaced as well, e.g.,
```
#define FFTE_ALGO_HPP
```

Also there are naming conventions and while your one is a valid one, heFFTe uses a different convention.

**Comment by dannys4** [comment]
This is now at least temporarily addressed in commit [ab63d08165a0c45187da80da0ce28bc7f1dcc2fa](https://github.com/dannys4/FFT-Research-F20/commit/ab63d08165a0c45187da80da0ce28bc7f1dcc2fa). I believe this design scheme is at least consistent and it makes sense.
